### ISSUE TITLE
Error obtaining SOA, when domain is a CNAME

### ISSUE THREAD

**Issue by ernestothorp** [globocom/kryptacme#34]
When trying to create a certificate for a domain that is configured as a CNAME, the DNS resolver is returning the SOA from the destination Domain, not from the origin.
Certificate creation fails with the following stack trace.
`undefined method `name' for nil:NilClass
/lib/local_acme.rb:176:in `get_domain_root'
/lib/local_acme.rb:182:in `add_domain_with_records'
/lib/local_acme.rb:125:in `add_dns_txt'
/lib/local_acme.rb:35:in `request_cert'
/app/jobs/certificates_create_job.rb:10:in `perform'
`

**Comment by tuxmonteiro** [comment]
Fixed
